### ISSUE TITLE
LTIP-2

### ISSUE THREAD

**Issue by westonnelson** [Layer2DAO/Layer2DAO#1]
I think this looks good - simple and short. 
Nice work...! 

Should lead to some engaging discussion in Discord which is I think primary goal as momentum continues to grow and can make any adjustments based on community feedback / discussion before proceeding to a vote.

Couple quick things I noticed in the repo: 

We should get the smart contract addresses added for Optimism for both pools that are live (BeethovenX and Velodrome) as well as the $L2DAO token contract address added. I'm only seeing Arbitrum still.

**Comment by Layer2DAO** [comment]
Good catch on the repo overview page being out of date. We'll get that updated.

**Comment by westonnelson** [comment]
Regarding Snapshot:

https://github.com/snapshot-labs/snapshot/blob/develop/src/plugins/quorum/examples.json

Good potential example here I think for review.
